### ISSUE TITLE
请问有木有旧版ssr_node_c7.sh可以下载鸭？

### ISSUE THREAD

**Issue by shap2zj** [Toxic-Cat/Airport-toolkit#16]
面板和数据库都没变，之前安装完成后，可以正常用。然后这两天用同样的Centos版本，同样的指令，再新建就都不能用了。。

试了NiTian1207的一键安装包版本，又正常使用。但是NiTian1207的安装包是一年前的 ，不支持单端口。
估计是大佬您更新了一些东西，。。请大佬麻烦提供一下旧版ssr_node_c7.sh救我狗命。蟹蟹

**Comment by shap2zj** [comment]
哦！我从我的另一台小鸡上面传了12月28号曾经下载过的ssr_node_c7.sh，当使用的wget指令，就留了备份。传到新机器安装后一切正常。。（服务器是干净阿里云香港+最新CentOS7 & 干净微软云香港+最新CentOS7）
大佬您最近是不是在测试新功能呀，很期待哦~
我帮您关掉这个issue了凹。实在不好意思占了一个issue号码。嘻嘻

**Comment by Toxic-Cat** [comment]
因爲新版本的centos7安裝脚本引用了一個新的後端，之後C7的部分會集成一個安裝python3的功能，這樣徹底解決兼容性問題。

**Comment by shap2zj** [comment]
刚才试了一下DigitalOcean
全程没有红字error出现。不过最后好像有一个not callable：
<img width="743" alt="截屏2020-01-13下午12 57 08" src="https://user-images.githubusercontent.com/22309477/72283359-39759e00-3604-11ea-8dc0-fca949b26347.png">
然后安装完之后status显示：
<img width="996" alt="截屏2020-01-13下午12 58 39" src="https://user-images.githubusercontent.com/22309477/72283467-7346a480-3604-11ea-8a6d-61d6ba7de034.png">
我一会换centos8系统再试试。嘻嘻

**Comment by cntaoge** [comment]
> 因为新版本的centos7安装脚本引用了一个新的替代，之后C7的部分会集成一个安装python3的功能，这样彻底解决兼容性问题。

我在我的VPS上没能运行起来。安装完成后进程里没有服务。试了很多次都是这样。CENTOS7的

**Comment by JH2628** [comment]
centos7的要用 159e3082 这个版本才会正常，后续的在我这里都运行不起来，centos8的没问题
先wget https://raw.githubusercontent.com/SuicidalCat/Airport-toolkit/159e3082/ssr_node_c7.sh
再chmod +x ssr_node_c7.sh
然后再修改chmod +x ssr_node_c7.sh，把里面的master版改为159e3082
这样运行./ssr_node_c7.sh安装，就可以正常运行了

**Comment by JH2628** [comment]
> centos7的要用 [159e308](https://github.com/Toxic-Cat/Airport-toolkit/commit/159e30823bda1fb4f9802ff6e83f3744b4d9beb8) 这个版本才会正常，后续的在我这里都运行不起来，centos8的没问题
> 先wget https://raw.githubusercontent.com/SuicidalCat/Airport-toolkit/159e3082/ssr_node_c7.sh
> 再chmod +x ssr_node_c7.sh
> 然后再修改chmod +x ssr_node_c7.sh，把里面的master版改为159e3082
> 这样运行./ssr_node_c7.sh安装，就可以正常运行了

把225行的 https://raw.githubusercontent.com/SuicidalCat/Airport-toolkit/master/ssr_node.service.el7 改为 https://raw.githubusercontent.com/SuicidalCat/Airport-toolkit/159e3082/ssr_node.service.el7

**Comment by Toxic-Cat** [comment]
> > 因为新版本的centos7安装脚本引用了一个新的替代，之后C7的部分会集成一个安装python3的功能，这样彻底解决兼容性问题。
> 
> 我在我的VPS上没能运行起来。安装完成后进程里没有服务。试了很多次都是这样。CENTOS7的

我這邊在CentOS 7.7 minimal的安裝上面測試過是沒有問題的，如果是service沒有起來的問題請先測試在安裝目錄 /soft/shadowsocks 直接用 python3 server.py 測試能不能正常啓動server本身。

**Comment by Toxic-Cat** [comment]
以及目前的主要支援對象將會轉向CentOS 8，如果有條件的話還是建議更新節點系統版本避免奇怪的問題。
