### ISSUE TITLE
ssr_node_c7.sh webAPI方式token 写入后缺少引号

### ISSUE THREAD

**Issue by GaryH4** [Toxic-Cat/Airport-toolkit#17]
https://github.com/Toxic-Cat/Airport-toolkit/blob/0982f2cf4fc60f73fd7ff073723e0e702553e325/ssr_node_c7.sh#L160

maybe:
`WEBAPI_TOKEN = "${webapi_token}"` -> `WEBAPI_TOKEN = '${webapi_token}'` ?

**Comment by Toxic-Cat** [comment]
Fixed.
