### ISSUE TITLE
日志文件的位置

### ISSUE THREAD

**Issue by lsbjkc** [Toxic-Cat/Airport-toolkit#4]
你好，请问这个脚本默认日志文件保存在哪里

**Comment by Toxic-Cat** [comment]
@lsbjkc 默認不提供日誌保存功能

**Comment by lsbjkc** [comment]
> @lsbjkc 默認不提供日誌保存功能
如果开启日志要怎么操作，特别是调试或查错，以及应对欺诈之类的场景需要用到

**Comment by lsbjkc** [comment]
我有个阿里云服务器用于游戏加速器，1核1G，centos7的系统，限速3Mbps。大概每隔一天就会出现一次内存占满的情况，即使我采用定时任务在每天凌晨6点重启服务，请问这是不是ssserver的bug？
![image](https://user-images.githubusercontent.com/43370337/56968438-bc99b580-6b95-11e9-9b9f-b4e4f7e57a15.png)
