### ISSUE TITLE
新版本没有执行安装

### ISSUE THREAD

**Issue by ETOCheney** [Toxic-Cat/Airport-toolkit#7]
你好，刚刚看了一下新版本没有安装ssr的命令。

**Comment by ETOCheney** [comment]
脚本缺少判定系统是否安装pip的地方，centos7新系统还需要再安装pip。

**Comment by Toxic-Cat** [comment]
>没有安装ssr

typo, fixed

>脚本缺少判定系统是否安装pip的地方

may add later
