### ISSUE TITLE
逻辑判断问题

### ISSUE THREAD

**Issue by ETOCheney** [Toxic-Cat/Airport-toolkit#8]
https://github.com/Toxic-Cat/Airport-toolkit/blob/d717ad4c04093c7b5a50c527a3513fd317f3bbda/ssr_node_c7.sh#L80
https://github.com/Toxic-Cat/Airport-toolkit/blob/d717ad4c04093c7b5a50c527a3513fd317f3bbda/ssr_node_c7.sh#L258
逻辑判断错误，导致安装过程百分百退出。

**Comment by ETOCheney** [comment]
https://github.com/Toxic-Cat/Airport-toolkit/blob/d717ad4c04093c7b5a50c527a3513fd317f3bbda/ssr_node_c7.sh#L258
缺少空格导致报错

**Comment by Toxic-Cat** [comment]
https://github.com/Toxic-Cat/Airport-toolkit/commit/9ca00d8e7cf0883589b77d7f70fe40f70b3fb4a7
